services:
  video-thumbnailer:
    image: sambresseleers/video-thumbnailer:latest
    container_name: video-thumbnailer
    environment:
      INPUT_DIR: /media
      ROWS: 4
      COLS: 5
      WIDTH: 1920
      QUALITY: 2
      FONT_SIZE: 18
      EXTENSIONS: "mp4|mkv|avi|mov|ts"
    volumes:
      - /mnt/user/media:/media
    restart: "no"
